import { test, expect } from '@playwright/test';

test.describe('Printable Clearance Record QA', () => {
  test('Student A can view and print the prototype clearance record', async ({ page }) => {
    await page.goto('/login');
    await page.getByLabel(/email address/i).fill('student.a@example.test');
    await page.getByLabel(/password/i).fill('password123');
    await page.getByRole('button', { name: /log in/i }).click();

    await page.waitForURL('**/student/dashboard');
    await expect(page.getByRole('heading', { name: /welcome back/i })).toBeVisible();

    const printButton = page.getByRole('button', { name: /print|preview|certificate/i });
    await expect(printButton).toBeEnabled();
    await printButton.click();

    await page.waitForURL('**/student/clearance/**/print');
    await expect(page.getByRole('heading', { name: /student clearance record/i })).toBeVisible();
    await expect(page.getByText('PROTOTYPE / MVP', { exact: true })).toBeVisible();

    await expect(page.getByText('STUD-2026-0001')).toBeVisible();
    await expect(page.getByText(/Pambayang Kolehiyo ng Mauban/i).first()).toBeVisible();

    const record = page.getByTestId('printable-clearance-area');
    await expect(record.getByText(/prototype record generated by the ASCS capstone MVP/i)).toBeVisible();
    await expect(record.locator('header')).toContainText('A.Y. 2026-2027');
    await expect(record.locator('header')).toContainText('FIRST SEMESTER');
    await expect(record.getByRole('heading', { name: /required signatory clearance/i })).toBeVisible();
    await expect(record.getByRole('heading', { name: /financial accountability review/i })).toBeVisible();
    const signatoryTable = record.getByRole('table', { name: /required signatory clearance/i });
    await expect(signatoryTable.locator('thead th')).toHaveText([
      'Office / Requirement',
      'Status',
      'Assigned Signatory',
      'Remarks',
      'Date Reviewed',
    ]);
    await expect(signatoryTable.locator('tbody tr')).toHaveCount(5);
    await expect(signatoryTable.getByText(/accountant/i)).toHaveCount(0);
    await expect(record.getByText(/librarian/i).first()).toBeVisible();
    await expect(record.getByText(/osa coordinator/i).first()).toBeVisible();
    await expect(record.getByText(/guidance counselor/i).first()).toBeVisible();
    await expect(record.getByText(/area chair/i).first()).toBeVisible();
    await expect(record.getByText(/adviser/i).first()).toBeVisible();
    await expect(record.getByText(/accountant review is a separate financial gate/i)).toBeVisible();
    await expect(record.getByText(/not an official institutional clearance certificate/i)).toBeVisible();
    await expect(record.getByText(/dean/i)).toHaveCount(0);
    await expect(record.getByText(/signed on|institution seal placeholder/i)).toHaveCount(0);

    await page.emulateMedia({ media: 'print' });
    await expect(record).toBeVisible();

    const printToolbar = page.locator('.print\\:hidden');
    await expect(printToolbar).toBeHidden();
  });
});
